name: 🚀 Deploy website on push on V2 branch
on:
 push:
  branches:
   - v2
 
jobs:
  web-deploy:
    name: 🎉 Deploy V2
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code V2
      uses: actions/checkout@v2

    - name: Use Node.js 16 V2
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: 🔨 Build Project V2
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files V2
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:          
        local-dir: ./build/
        server: ham.qrits.com.ar
        username: integrationv2@ham.qrits.com.ar
        password: ${{ secrets.ftp_password_v2 }}
        
