on: push

name: 🚀 Deploy website on push

push:
 branches:
      - v2
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:          
        local-dir: ./build/
        server: ham.qrits.com.ar
        username: integrationv2@ham.qrits.com.ar
        password: ${{ secrets.ftp_password }}
        
